### ISSUE TITLE
Clone repo example doesn't release all file system locks as written

### ISSUE THREAD

**Issue by bdw429s** [centic9/jgit-cookbook#11]
https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CloneRemoteRepository.java

Please see this SO question and answer:
http://stackoverflow.com/questions/31764311/how-do-i-release-file-system-locks-after-cloning-repo-via-jgit/31764312#31764312

If my fix is in fact the correct fix, please let me know and I will submit a pull request for this cookbook example.

**Comment by centic9** [comment]
Yes, a PR would be nice, although it seems JGit should at least adjust the javadoc here as well.

**Comment by centic9** [comment]
Fixed via #12
