### ISSUE TITLE
A snippit to list files in a folder based on a tag would be super handy

### ISSUE THREAD

**Issue by dkowis** [centic9/jgit-cookbook#13]
Like I want all the files in `src/main/java/some/package` at tag `v1.0`.

I'm having trouble figuring out this kind of operation with TreeWalk. I get really close, but not quite.

**Comment by AlphaJuliettOmega** [comment]
yes, please :+1: 
i'm struggling too.
please come back if you figured it out

**Comment by centic9** [comment]
This should be available via commit https://github.com/centic9/jgit-cookbook/commit/88f89f3b42ef11b930856cc89c56e3481826ce98, take a look at the new snippet at https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/api/ListFilesOfCommitAndTag.java
