### ISSUE TITLE
What are the difference between the two ways of opening a Git repository besides the 'close' difference?

### ISSUE THREAD

**Issue by JordanMartinez** [centic9/jgit-cookbook#19]
I've noticed in your code that you will often use these lines to open a git repository:
````java
FileRepositoryBuilder builder = new FileRepositoryBuilder();
Repository repository = builder.setGitDir(repoDir)
                .readEnvironment() // scan environment GIT_* variables
                .findGitDir() // scan up the file system tree
                .build()
Git git = new Git(repository);
````
I've tried another way using the factory methods:
````java
Git git = Git.init().setGitDir(repoDir).call();
````
In the first way, it seems you need to call `repository.close()` and `git.close()` in order to fully close the resources. In the second way, since it was initialized using the factory method, only `git.close()` needs to be called, right?

My question is, besides the note I mentioned above, are there any other differences between the two?

**Comment by centic9** [comment]
There is no big difference, it rather depends if you will need a Git() object for doing porcelain commands or if you rather would like to only work with the underlying direct API. 

Some of the samples use the double allocation when I am working with both the Git-object but also the Repository. 

I'll update the Init-sample somewhat to show why this is done a bit better...

**Comment by JordanMartinez** [comment]
Thanks, that makes sense.
