### ISSUE TITLE
.JAR File issue

### ISSUE THREAD

**Issue by EugeneTan10** [centic9/jgit-cookbook#26]
Based on the example given, we have to import org.dstadler.jgit.helper.CookbookHelper in the project. But this will give me an error, I assumed that we need to include a specific .JAR file for CookbookHelper. However there is no specific file for this CookbookHelper in Google. 
Is there any solution for this particular problem? Any help will be appreciated !

**Comment by eugener** [comment]
It is a part of repository:
https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/helper/CookbookHelper.java

**Comment by centic9** [comment]
This project is not intended to be used as a library via a .jar-file, but tries to provide snippets that you can copy into your project as a starting point. None of the examples does a really useful thing, they just show how JGit can be used to achieve certain things related to working with Git repositories from within Java applications.

Furthermore `CookbookHelper` is just an internal class that is used to create/open repositories for the examples. If you think one of the methods is useful it is likely best to simply copy the few lines from there into your code.
