### ISSUE TITLE
Show changed files between two commits without a local clone

### ISSUE THREAD

**Issue by mykevinjung** [centic9/jgit-cookbook#29]
Hello,

I've got a lot of help from your porcelain commands.  I much appreciated.

Now I am in a situation where I need to get changed files between commits (similar to ShowChangedFilesBetweenCommits) but **without a local clone**.  I need to check the commits across multiple git repositories and some of the repositories are so big like more than 1GB.  I need to clean up my local repo once I get the information.  So cloning the repository each time to get the changed file information is too costly.  I wonder if there is any way to get the changed file information remotely, just like we can see the changed files on a commit on github.com online.

Thank you so much in advance!
Kevin

**Comment by centic9** [comment]
As stated in the README I am not able to provide help with specific problems/questions with JGit as part of this repository, please post questions at http://stackoverflow.com/questions/tagged/jgit where many more very knowledgeable people are answering questions like this one.

**Comment by mykevinjung** [comment]
Got it.  Thank you!
