### ISSUE TITLE
Why there is not functin name after @@ when I use show file difference

### ISSUE THREAD

**Issue by sdrgroup** [centic9/jgit-cookbook#30]
When I use the example of ShowFileDiff, I can get the details of difference, but there is not function name follows @@, which is different from git diff. Are there any metrics I can set? I need to get the function name. Thank you.

**Comment by centic9** [comment]
As stated in the README I cannot provide Guidance on usage of JGit here, please use Stackoverflow questions, where you have a much better chance of a good answer as many more people watch those questoins than issues in this project!
