### ISSUE TITLE
Example using GitServlet?

### ISSUE THREAD

**Issue by buko** [centic9/jgit-cookbook#32]
It would be great if there was a snippet around using GitServlet.

It looks like JGit has support for serving up git repos over http but documentation on exactly how to do this is few and far between. There's some unit tests and other projects (eg gitblit) but a simple, short snippet would be great.

**Comment by centic9** [comment]
Some initial pointers that I found:

* https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit.http.server/src/org/eclipse/jgit/http/server/GitServlet.java
* https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit.junit.http/src/org/eclipse/jgit/junit/http/SimpleHttpServer.java
* http://de.slideshare.net/msohn/jgit-egitcoolnewstuff

JGit seems to provide a SimpleHttpServer (which is using Jetty as servlet container) which quite nicely shows how this can be done. I'll take a closer look, but not sure if another sample would provide any additional gain here...

**Comment by buko** [comment]
There are some unit tests out there... but they're not the easiest thing to follow. It would be nice if there was a simple example that showed creating a (simple file-based) repository and then serving it up on the port.

**Comment by chalstrick** [comment]
The JGit commandline has a daemon command which starts a server. The code
which you can find in
https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit.pgm/src/org/eclipse/jgit/pgm/Daemon.java
is definitly not minimal ... but the run() method shows what to do.

Ciao
  Chris
