### ISSUE TITLE
The files I delete from disk and how to update the repo?

### ISSUE THREAD

**Issue by lsj9383** [centic9/jgit-cookbook#33]
For example, how to run "git add ." or "git add -u" by JGit?
Tks

**Comment by lsj9383** [comment]
OK I get [it](https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/CleanUntrackedFiles.java).

**Comment by centic9** [comment]
So this is resolved, right?

**Comment by lsj9383** [comment]
yes, ok, tks.
