### ISSUE TITLE
countFiles or countLines?

### ISSUE THREAD

**Issue by tgkprog** [centic9/jgit-cookbook#35]
In https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/ShowBlame.java

Is the method  private static int countFiles(Repository repository, ObjectId commitID, String name) throws IOException counting lines or counting files? If lines then why is it called countFiles?

I'm trying to understand how to use BlameCommand and your examples are useful for my over all git and jgit understanding. Thank you. Just confused it this a typo or am I missing something?

I'm trying to use jGit to tell me who is the author or authors of a set of lines of a file. Understanding your work would help.

**Comment by centic9** [comment]
It counts the number of lines of the file as-of the particular commit that is selected. See the updated snippet which now has some more comments/output.
