### ISSUE TITLE
Illustrate support for JGit server in integration tests

### ISSUE THREAD

**Issue by gberche-orange** [centic9/jgit-cookbook#39]
Thanks for this great repo. This really helped me with using jgit. As I was trying to write integration tests for my code using jgit as a client, I struggled find the right syntax for starting an embedded jgit server without the burden of fetching a servlet container when using the [gitservlet](https://github.com/centic9/jgit-cookbook#gitservlet)

If this can help, here is the syntax I ended up using
https://github.com/orange-cloudfoundry/cf-ops-automation-broker/blob/ac8650892a25409ba8d410fb5fad3b5c5a24938a/cf-ops-automation-broker-core/src/main/java/com/orange/oss/cloudfoundry/broker/opsautomation/ondemandbroker/git/GitServer.java#L36-L118

A simple example of starting the jgit server in an integration test
https://github.com/orange-cloudfoundry/cf-ops-automation-broker/blob/ac8650892a25409ba8d410fb5fad3b5c5a24938a/cf-ops-automation-cloudflare-broker/src/test/java/com/orange/oss/cloudfoundry/broker/opsautomation/ondemandbroker/cloudflare/CloudFlareServiceProvisionningTest.java#L60-L84

Please let me know if this could be useful for others and whether a PR would help.

**Comment by centic9** [comment]
Yes, sure, a PR would be highly welcome!

**Comment by centic9** [comment]
I have added links to the README to point to the implementation of JGitServer in cf-ops-automation-broker to not duplicate this code here.
