### ISSUE TITLE
Git add not working  through jgit

### ISSUE THREAD

**Issue by marwb** [centic9/jgit-cookbook#41]
Hi 
jgit version:compile group: 'org.eclipse.jgit', name: 'org.eclipse.jgit', version: '4.10.0.201712302008-r'

Trying to do:Rename .sql files in project structure before they are pushed to repo.To achieve this,I have written a pre commit hook where I am trigerring a gradle run task which invokes a java programme that by using JGIT API finds files ending with .sql (new modified)and renames them in proper naming format.

In this I am using git add API to add newly renamed file to git index and I expect that newly renamed and added file should also be commited when git commit runs.But this is not happening and newly renamed file is showing under untracked files.
https://stackoverflow.com/questions/48704380/git-pre-commit-hook-triggering-gradle-run-task-which-renamed-files-in-db-migrati

Stackover flow link where I have given full description.

 
[SelfContainedExample.txt](https://github.com/centic9/jgit-cookbook/files/1719649/SelfContainedExample.txt)
[GitStatusFileAndRename.txt](https://github.com/centic9/jgit-cookbook/files/1719650/GitStatusFileAndRename.txt)

**Comment by centic9** [comment]
See the note on the Frontpage of this repository, I cannot answer JGit usage questions here, please use only Stackoverflow to discuss this, therefore I am closing this.

_Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally._
