### ISSUE TITLE
How to achieve fork function?

### ISSUE THREAD

**Issue by TonnyCheng** [centic9/jgit-cookbook#42]
hi ,i want achieve git fork function base on java language,just like "git remote add upstream<other remote repository>" to my remote repository,do you have any example? I did not find it

**Comment by centic9** [comment]
Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.
