### ISSUE TITLE
How to implement the revert after merger

### ISSUE THREAD

**Issue by sh20104510** [centic9/jgit-cookbook#46]
How to implement the revert after merger

**Comment by centic9** [comment]
As described on the main-page and the issue-template, this issue-tracker is not for general questions about JGit: 

_Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally._
