### ISSUE TITLE
bad  code

### ISSUE THREAD

**Issue by lingfengsan** [centic9/jgit-cookbook#49]
*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*

https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/OpenRepository.java
The last line "FileUtils.deleteDirectory(dir);" delete all my code!Thanks to I hava push to my git rep!

**Comment by centic9** [comment]
I am sorry that it caused you data-loss, but obviously you adjusted the code to do something different as in the original version it only removes a freshly created test-repository which is safe to delete, not anything else unless the code is modified so that it does something different.
