### ISSUE TITLE
I had problems opening a existing repository and found the problem

### ISSUE THREAD

**Issue by JuhoKang** [centic9/jgit-cookbook#5]
I'm not that good at using forking, pull requests so i will comment this here

at
OpenRepository.java

```
FileRepositoryBuilder builder = new FileRepositoryBuilder();
Repository repository = builder.setGitDir(new File("/my/git/directory"))
            .readEnvironment() // scan environment GIT_* variables
            .findGitDir() // scan up the file system tree
            .build();

System.out.println("Having repository: " + repository.getDirectory());

repository.close();
```

this part doesn't work properly
i tried to get a status from my own repository but problems occured that my repository is bare but it isn't

if i try to get a status from this repository it assumes the repo bare
so this means it's not properly opened

It should be changed just a little

I think setGitDir() method is for making a new Repository and this occurs the problem

the source like this works properly(didn't tested a lot but status call works properly)

```
FileRepositoryBuilder builder = new FileRepositoryBuilder();
Repository repository = builder.findGitDir(new File("/my/git/directory"))
            .readEnvironment() // scan environment GIT_* variables
            .build();

System.out.println("Having repository: " + repository.getDirectory());

repository.close();
```

please respond and update the cook-book if this is right
sorry for bad english =)

**Comment by 2dxgujun** [comment]
https://github.com/centic9/jgit-cookbook/issues/5#issuecomment-51107996

**Comment by blachworld** [comment]
0000
#47

**Comment by blachworld** [comment]
11111#46

**Comment by acevedo93** [comment]
> Thanks for the note, yes, the snippet was misleading and not fully working out of the box. I adjusted it to make it a fully working piece and show the actual directory that is required for this to work.

**Comment by acevedo93** [comment]
https://github.com/centic9/jgit-cookbook/issues/5#issuecomment-51107996

fdafdafdaf

**Comment by prithvisrinivasan** [comment]
https://github.com/centic9/jgit-cookbook/issues/5#issuecomment-51084491

**Comment by playbazaarofficial** [comment]
https://chick-fil-a-info.com
