### ISSUE TITLE
how to read content from remote repo

### ISSUE THREAD

**Issue by johnsonin** [centic9/jgit-cookbook#50]
i just want to read content from a file in the remote repo..I do not want to clone the repo first.
i find no idea to do this.
thx..

**Comment by centic9** [comment]
Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.
