### ISSUE TITLE
When I want to submit an operation to delete a file, I find that I cannot submit

### ISSUE THREAD

**Issue by ankuo** [centic9/jgit-cookbook#71]
Thanks for this great repo. This really helped me with using jgit. 
version:
<dependency>
            <groupId>org.eclipse.jgit</groupId>
            <artifactId>org.eclipse.jgit</artifactId>
            <version>5.5.0.201909110433-r</version>
 </dependency>
When I want to submit an operation to delete a file, I find that I cannot submit.
I found a change by executing 'git status'

`On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    gitlab-ci/fdev-deploy.properties

no changes added to commit (use "git add" and/or "git commit -a")`

then; I execute code via jgit
 
            git.add().addFilepattern(".").call();
            git.commit().setMessage(filename).call();
            git.push().setRemote("origin").setCredentialsProvider(provider).call();

Finally, the operation of deleting my files was not submitted to the remote warehouse

**Comment by centic9** [comment]
I would check the state of the repository after the "add" command. Does it properly list the removal of the file as being "staged"? If not, then you need to do the "delete a file from git" differently, although I do not know how that is done as I did not encounter this yet for my projects.

But in general please follow the note for this repository and issue template about asking questions about JGit:

Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.

Therefore I am closing this here, please post the question on stackoverflow, you surely will get help there.
