### ISSUE TITLE
The question about commit

### ISSUE THREAD

**Issue by xuweichuan** [centic9/jgit-cookbook#73]
Hello, is it possible to use jgit to commit local changes to another specified branch without switching to the specified branch?

**Comment by centic9** [comment]
not as far as I know of, and please use stackoverflow for questions about jgit usage as specified in the issue-guidelines:

*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*
