### ISSUE TITLE
fetch tags via commitId

### ISSUE THREAD

**Issue by zhangbaomingege** [centic9/jgit-cookbook#76]
*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*

**Comment by centic9** [comment]
No actual comment, just the issue-template, closing for now as it seems to be spam/miss-clicking.
