### ISSUE TITLE
How to get the line number of a file diff

### ISSUE THREAD

**Issue by Kisen-Chin** [centic9/jgit-cookbook#78]
Hi All,
I would like to use jgit to operate my git. Now I meet a problem that, how could I get the changed line number using Jgti.
For now, the jgit return a string like this:
==============================
diff --git a/pom.xml b/pom.xml
index 5d79f75..6d223e2 100644
--- a/pom.xml
+++ b/pom.xml
@@ -161,3 +161,5 @@
     </build>
 
 </project>
+
+test added here
==============================

can jgit return the line number before  "+test added here" ?
Eg.
===============================
diff --git a/pom.xml b/pom.xml
index 5d79f75..6d223e2 100644
--- a/pom.xml
+++ b/pom.xml
@@ -161,3 +161,5 @@
     </build>
 
 </project>
+ **line 98**
+ **line 99** test added here

**Comment by centic9** [comment]
You likely need to look at how the JGit implementation performs the rendering of the diff as it seems there is no API to get this information directly.

Please also take note of my statement regarding issues here: 

> Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.

Therefore I am clising this here, please ask on stackoverflow if you need more information/help with JGit itself.
