### ISSUE TITLE
 SSL authentication

### ISSUE THREAD

**Issue by bb2b2bb** [centic9/jgit-cookbook#80]
Secure connection to https://xxxx/xxxx.git could not be established because of SSL problems

How to skip SSL authentication
tks~

**Comment by centic9** [comment]
As mentioned in the README and in the issue template: 
*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*

So please use StackOverflow for these types of questions.
