### ISSUE TITLE
using FileRepositoryBuilder with setGitDir() does not return valid submodule Repository

### ISSUE THREAD

**Issue by vladak** [centic9/jgit-cookbook#81]
The approach to get a `Repository` object for a sub-repository on https://github.com/centic9/jgit-cookbook/blob/1e668bc51ef457bbd8e219b1448bf6292c8c6bcb/src/main/java/org/dstadler/jgit/unfinished/TestSubmodules.java#L45-L52 
does not work.

I am aware this is under `unfinished` however it seems to be used out there and leads to confusion as illustrated on https://stackoverflow.com/questions/26090139/jgit-reading-commits-from-a-submodule

The suggestion below the SO answer is to use absolute path for the `setGitDir()` call however that does not help. The problem is that `gitDir` property is persistent w.r.t. `findGitDir()` and the resulting `Repository` object will have something like `/tmp/gitinit9778898520347794239.test/testrepo/.git` while it should have `/tmp/gitinit9778898520347794239.test/.git/modules/testrepo`. As a result, calls like `subRepo.getBranch()` will return `null`.

To fix this, replace the try-with-resources block with 
```java
Repository subRepo = SubmoduleWalk.getSubmoduleRepository(mainRepo, "testrepo");
```
and perhaps add some assert other than `isBare()`.

**Comment by centic9** [comment]
Thanks for the note, I have applied the changes to the snippet, although I left it in "unfinished" as I lack the time to build it out into a more complete snippet.
