### ISSUE TITLE
How to manage ssh key?

### ISSUE THREAD

**Issue by cens7** [centic9/jgit-cookbook#83]
Can I manage ssh key with JGit?  We can manage users ssh key in github or gitlab ,But I don't know JGit to work. 

I'm suspecting this is a dumb question, but however can't seem to find the answer...
Thanks.

**Comment by centic9** [comment]
Did you actually do a quick search for the information first? A search with Google pops up many results, e.g. https://www.codeaffine.com/2014/12/09/jgit-authentication/ seems to explain this in lots of detail.

In general, please use sites such as http://stackoverflow.com/ for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.
