### ISSUE TITLE
LFS

### ISSUE THREAD

**Issue by nWidart** [centic9/jgit-cookbook#84]
Hello,

Thank you for this repository, very helpful!
I'm working with a repository setup using LFS. When cloning the repository with jgit, it doesn't however resolve the large files indexed with LFS.

With my local git client which has LFS installed & configured, when I clone, I have the large files cloned with it.

From my research, it looks like jgit supports LFS, but I can't seem to find any indicators as to how to setup it up / use it.

Would you have any pointers here?

Thank you,

**Comment by centic9** [comment]
As mentioned in the README and in the issue-template, I do not provide "how to use feature XYZ" type of support here. 

*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*

If you find out, I would be eager to receive PRs adding some snippets if applicable, but I expect that LFS should work "out of the box" with jgit and not require any special code at all.
