### ISSUE TITLE
JGitInternalException ERROR Creating lock file Too many open files

### ISSUE THREAD

**Issue by lashnag** [centic9/jgit-cookbook#87]
Hi! Could you help me with cloning error? I have got error Creating lock file failed when try to clone more than 2000 repositories

https://stackoverflow.com/questions/73839579/jgitinternalexception-error-creating-lock-file-too-many-open-files

**Comment by centic9** [comment]
As stated in the README and in the issue template:

_Note: Please use sites such as http://stackoverflow.com/ for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally._

This also means that it is not useful to create issues with links to stackoverflow discussions here.
