### ISSUE TITLE
git branch --set-upstream-to=origin/1.0.0 master

### ISSUE THREAD

**Issue by Lailah123** [centic9/jgit-cookbook#88]
How do you write it in jgit?

**Comment by centic9** [comment]
Please read the text that is presented to you when you create an issue here:

*Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally.*
