### ISSUE TITLE
Conflict detection

### ISSUE THREAD

**Issue by wise-coders** [centic9/jgit-cookbook#89]
I would like to detect conflicts ( by push and probably by pull ) . I mean situations when:
- I try to commit and push a file which was already modified prior by another user in GIT
- I try to do a pull and my file was modified.
How can I list this files, and mark them as merged after I edited them?

**Comment by centic9** [comment]
I'd probably take a look at https://github.com/centic9/jgit-cookbook/blob/master/src/main/java/org/dstadler/jgit/porcelain/MergeChanges.java , it shows how to get conflicts when doing a merge and push/pull basically are doing merge/rebase internally.

However please stick to what the issue-template and the README state and discuss questions of "how do I do XXX in JGit" elsewhere:

_Note: Please use sites such as http://stackoverflow.com for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally._

**Comment by wise-coders** [comment]
Thank you for your help. I created an StackOverflow thread, soon will be active.

Also, I tested this code snippet after commit and before push, and the merge.getConflicts() returns a null value.

```
ObjectId mergeBase = git.getRepository().resolve("changes");
                        MergeResult merge = git.merge().
                                include(git.getRepository().resolve(Constants.HEAD)).
                                setCommit(true).
                                setFastForward(MergeCommand.FastForwardMode.NO_FF).
                                setMessage("Merged changes").
                                call();
                        System.out.println("Merge-Results for id: " + mergeBase + ": " + merge);
                        for (Map.Entry<String,int[][]> entry : merge.getConflicts().entrySet()) {
                            System.out.println("Key: " + entry.getKey());
                            for(int[] arr : entry.getValue()) {
                                System.out.println("value: " + Arrays.toString(arr));
                            }
                        }
```
