### ISSUE TITLE
Support ed25519 SSH using Apache MINA SSHd

### ISSUE THREAD

**Issue by thachlp** [centic9/jgit-cookbook#92]
Since JGit 5.2, JGit provides an alternative SSH transport implementation based on Apache MINA SSHd, which supports ed25519 which is currently not supported by JSch.
Here is the code example demonstrate: https://dzone.com/articles/jgit-library-examples-in-java

**Comment by centic9** [comment]
Thanks for the suggestion, added snippet `CloneRemoteRepositoryWithApacheSSHD` now
