### ISSUE TITLE
How to view changes made to the workspace?

### ISSUE THREAD

**Issue by zyyBjtu** [centic9/jgit-cookbook#94]
I was checking the changes in the work area with jgit, but it seems like it can only compare changes between commits.

**Comment by centic9** [comment]
Please observe the note in the README and in the issue-template, Stackoverflow is a much better place for such questions: 

_Note: Please use sites such as http://stackoverflow.com/ for general questions about JGit usage, not issues in this project. Issues should be used for problems with snippets and suggestions of missing snippets. Snippets from good answers on stackoverflow can then be included here, naturally._
